#%RAML 1.0
title: HyperStorage API
baseUri: hb://hyperstorage
types:
  HyperStorageTransaction:
    type: object
    properties:
      transactionId: string

  HyperStorageTransactionCreated:
    type: object
    properties:
      transactionId: string
      path: string

  HyperStorageIndexSortOrder:
    enum: [asc, desc]

  HyperStorageIndexSortFieldType:
    enum: [text, decimal]

  HyperStorageIndexSortItem:
    type: object
    properties:
      fieldName: string
      fieldType?: HyperStorageIndexSortFieldType
      order?: HyperStorageIndexSortOrder

  HyperStorageIndex:
    type: object
    properties:
      indexId: string
      sortBy: HyperStorageIndexSortItem[]
      filterBy?: string

  HyperStorageIndexNew:
    type: object
    properties:
      indexId?: string
      sortBy: HyperStorageIndexSortItem[]
      filterBy?: string

  HyperStorageIndexCreated:
    type: object
    properties:
      indexId: string
      path: string

/content/{path}:
  uriParameters:
    path: string
  get:
    queryParameters:
      sortBy:
        type: string
        required: false
      filter:
        type: string
        required: false
      size:
        type: integer
        required: false
      skipMax:
        type: integer
        required: false
    responses:
      200:
  put:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction
      201:
        body:
            application/json:
              type: HyperStorageTransactionCreated
  patch:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction
  delete:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction
  post:
    responses:
      201:
        body:
            application/json:
              type: HyperStorageTransactionCreated
  feed:put:
  feed:patch:
  feed:delete:

/transactions/{transactionId}:
  uriParameters:
    transactionId: string
  get:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageTransaction

/indexes/{path}:
  uriParameters:
    path: string
  post:
    body:
      application/json:
        type: HyperStorageIndexNew
    responses:
      201:
        body:
          application/json:
            type: HyperStorageIndexCreated

/indexes/{path}/{indexId}:
  uriParameters:
    path: string
    indexId: string
  get:
    responses:
      200:
        body:
          application/json:
            type: HyperStorageIndex
  delete:
