#%RAML 1.0
title: HyperStorage API
baseUri: hb://hyperstorage-internal

types:
  NodeStatus:
    enum: [passive,activating,active,deactivating,lost]

  Node:
    type: object
    properties:
      node_id: string
      status: NodeStatus
      cluster_hash: integer

  NodeUpdated:
    type: object
    properties:
      source_node_id: string
      source_status: NodeStatus
      accepted_status: NodeStatus
      cluster_hash: integer

  NodesPostError:
    enum: [unknown-node,cluster-not-matches]

  RemoteTask:
    type: object
    properties:
      source_node_id: string
      task_id:
        type: number
        format: long
      key: string
      group: string
      ttl:
        type: number
        format: long
      expects_result: boolean
      task_headers: object
      task_body: string
      extra: object

  RemoteTaskResult:
    type: object
    properties:
      task_id:
        type: number
        format: long
      result_headers: object
      result_body: string
      extra: object

  BackgroundContentTask:
    type: object
    properties:
      document_uri: string

  BackgroundContentTaskResult:
    type: object
    properties:
      document_uri: string
      transactions: string[]

/node:
  get:
    responses:
      200:
        body:
          application/json: Node

/nodes:
  post:
    body:
      application/json: Node
    responses:
      200:
        body:
          application/json: NodeUpdated
      409:

/tasks:
  post:
    body:
      application/json:
        type: RemoteTask
    responses:
      202:

/task-results:
  post:
    body:
      application/json:
        type: RemoteTaskResult
    responses:
      202:

/background-content-tasks:
  post:
    body:
      application/json: BackgroundContentTask
    responses:
      200:
        body:
          application/json: BackgroundContentTaskResult
